### ISSUE TITLE
代码笔误bug

### ISSUE THREAD

**Issue by pertgame** [shiyanhui/dht#11]
routingtable.go 代码223行，kbucket.Replace函数里面，候选节点插入到nodes列表之后没有break

**Comment by shiyanhui** [comment]
bucket.nodes 是一个 KeyedDeque，iter遍历的时候我们使用的是sync chan，如果break了，那么chan就会堵塞，进而导致goroutine泄露。虽然可以使用buffer chan来解决，但是在KeyedDeque内部看，我们并不知道外部需要多大的buffer size。因此，最终采取这样的设计。

**Comment by shiyanhui** [comment]
Iter 代码在这里  https://github.com/shiyanhui/container/blob/master/syncedlist.go#L99

**Comment by pertgame** [comment]
soga,明白了

**Comment by shiyanhui** [comment]
有啥问题一起探讨哈，这个先关了 :)
