### ISSUE TITLE
Cannot crawl any data now

### ISSUE THREAD

**Issue by sackery** [shiyanhui/dht#15]

**Comment by yedawei007** [comment]
You can't use it in LAN

**Comment by sackery** [comment]
I used in VPS with ipv4

**Comment by shiyanhui** [comment]
Now dht can not run in a network hidden behind NAT yet . So if you run it in VPS, I guess maybe your VPS run in a virtual IP?

**Comment by ilcn** [comment]
Also make sure that if you use ufw or other firewall you open the port you are using.
