### ISSUE TITLE
速度太慢了吧，一天不重复的才2000多条

### ISSUE THREAD

**Issue by chengziqing** [shiyanhui/dht#16]
别人的一天都1200万条

**Comment by shiyanhui** [comment]
你是在局域网跑的么？还是用的vps？目前由于NAT的限制局域网内是几乎接收不到回复的。

关于跑的速度，你可以看下这个视频目测一下 https://www.youtube.com/watch?v=AIpeQtw22kc ， 我自己实际跑的情况是，一天差不多12万个左右不重复的。

『别人的一天1200万条』可以给个链接么？我也好学习研究改进一下。

**Comment by chengziqing** [comment]
@shiyanhui 我是在阿里云windows服务器上跑的，有数据，就是慢。我插入数据库，不重复，一天2000多，很稳定，跑了4天，今天看，才8000多条。
那个人直接说的，没开源。我看错了，是100多万一天。

**Comment by shiyanhui** [comment]
阿里云我没用过，不知道如何，共享IP？首先要弄清楚要下载一个种子的步骤：

- 第一步要监听得到种子的infohash和广播这条种子的服务器IP和Port。
- 第二步是根据这个种子的infohash去那个服务器IP:Port通过TCP把种子下载下来。

由于存在很多虚假的广播（比如很多种子爬虫），或者种子广播后用户直接关闭迅雷等BT客户端，或者网络原因等等，很多第一步得到的infohash其实在第二步是下载不下来的。

我说的12万是指12小时左右真正把种子下载下来的数量（去重后）。我猜测他说的100万那个数量是指第一步得到的广播数量？你可以再问问他？

**Comment by chengziqing** [comment]
@shiyanhui 阿里云也类似VPS,独立IP。
现在是不管是12万还是100万.我这2000的速度，实在太慢了。
你所说的下载种子是指得到infohash的详细信息，比如文件列表，文件大小等信息吗？
由于他留的言，并不清楚他的100万，是啥数据，应该是一个客观的数字

**Comment by shiyanhui** [comment]
@chengziqing 对，就是我们通常所说的种子。

**Comment by shiyanhui** [comment]
我用的vps是vultr，建议你用一下，这个issue先close了。
