### ISSUE TITLE
现在爬虫是不是已经不能正常工作了？

### ISSUE THREAD

**Issue by qsbaq** [shiyanhui/dht#18]
我按照你的示例来的，没有回显了。

**Comment by shiyanhui** [comment]
可以工作啊，保证你在public ip上跑

**Comment by qsbaq** [comment]
现在爬出来的种子好像很慢，可以多线程么？
示例代码：https://github.com/shiyanhui/dht/blob/master/sample/spider/spider.go

**Comment by JJJJJJJerk** [comment]
在阿里云服务器上跑 没有效果啊!

**Comment by shiyanhui** [comment]
@JJJJJJJerk 不是太清楚, 阿里云封BT协议?
