### ISSUE TITLE
请问作者如何入库

### ISSUE THREAD

**Issue by xvzhonglin** [shiyanhui/dht#21]
如标题这东西直接输出到显示器   怎么入库啊  而且获取到内容json  并不标准，  我很懵逼

**Comment by shiyanhui** [comment]
入库的话可以解析后存到数据库里边啊 json不标准是因为不同的bt客户端不一样

**Comment by xvzhonglin** [comment]
谢谢  我没准备直接入库  准备做分布式  在测试用重定向用crul 提交
