### ISSUE TITLE
Can I search keyword torrent metadata realtime?

### ISSUE THREAD

**Issue by kiemrong08** [shiyanhui/dht#22]
I want to search torrent metadata by keyword but only filter dht node have torrent i want and ignore dht node dont relevant. How can i do this ?
#request_feature

**Comment by shiyanhui** [comment]
Maybe BEP18 is what you want, http://www.bittorrent.org/beps/bep_0018.html, but it's deferred. For now, there isn't one Accepted BEP can do that.
