### ISSUE TITLE
比python的慢太多

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [shiyanhui/dht#23]
对比pyhton的
```
https://github.com/NanYoMy/DHT-simDHT
```
慢的不是一个数量级，先不考虑解析的话，对方是可能到达3天上千万的hashinfo的，你这个我加了OnGetPeers，在里面request，也一样慢的不行

**Comment by shiyanhui** [comment]
看这里 https://github.com/shiyanhui/dht#why-it-is-slow-compared-to-other-spiders-
