### ISSUE TITLE
Big God, May ask How to build all the source?

### ISSUE THREAD

**Issue by jinfagang** [shiyanhui/dht#24]
I want build it as a single binary executable file, so I run `go build` just inside dht/ but, it says:`can't load package: package dht: cannot find package "dht" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/dht (from $GOROOT)
	/Users/jintian/go/src/dht (from $GOPATH)` , What should I do?

**Comment by shiyanhui** [comment]
```shell
go get github.com/shiyanhui/dht/sample/spider
```

**Comment by jinfagang** [comment]
I using `go get github.com/shiyanhui/dht`, the source code download into `$HOME/go/src`, but I can not import from my own project, can not find `github.com/....`, I tried `go install ` not work. How to let IDE can import your project?

**Comment by jinfagang** [comment]
Hi, sorry for disturb, I build that spider, but, when runing, I got no result output, what I miss?
