### ISSUE TITLE
How to save torrent file via magnet

### ISSUE THREAD

**Issue by jinfagang** [shiyanhui/dht#26]
Hi, how to save torrent via magnet using this library?

**Comment by YibaiMeng** [comment]
This library can't do this: getting the torrent (or the infohash part of the torrent, to be precise), is part of the peer protocol's job. See http://www.bittorrent.org/beps/bep_0003.html for more detail.

**Comment by raspher** [comment]
Yup, issue is not related to DHT. You can get peers from dht, then download data from peers via torrent client (as a peer).

But you can write a simple script to check trackers for peers, then generate magnet from collected data. Magnet is a string which contains infohash and (usually) multiple trackers. Infohash can be used alone to download torrents in popular clients.

You can search trackers are on https://newtrackon.com/ . Some of them are buggy.

This issue should be closed @shiyanhui
