### ISSUE TITLE
节点分裂的问题

### ISSUE THREAD

**Issue by beck917** [shiyanhui/dht#27]
> } else if root.KBucket().prefix.Compare(nd.id, prefixLen-1) == 0 {

和你博客中说的好像有点差异 

> 第一种情况是当前的路径是该节点ID（注意不是要插入的key，是“我”自己的ID）的前缀，那么就分裂

代码中是用了要插入的node,而不是自己的nodeid,我理解下来应该是自己的nodeid

请问是我理解的问题吗

**Comment by shiyanhui** [comment]
你理解的没错, 理论是那样的. 这里实现的时候为了能够容纳更多的节点, 是按照被插入的节点插入的.

**Comment by beck917** [comment]
多谢了,明白了^^
