### ISSUE TITLE
Fix config.KBucketSize Size

### ISSUE THREAD

**Issue by luckcolors** [shiyanhui/dht#3]
In line 74 of dht.go and in other places regarding maxsize you are setting a value wich overflows int32.
Error: /gopath/src/github.com/shiyanhui/dht/dht.go:74: constant 4294967296 overflows int.
(this is run on an armv7 machine 32bits architecture)

**Comment by shiyanhui** [comment]
Hi, I have fixed it. Cause I don't have a 32-bits machine, could you help test it again? Thanks!

**Comment by luckcolors** [comment]
Yes. It works. Also would you mind writin in the readme.md the ram requirements and how these chage based on the crawler settings?.

You might want to set the default Kbucket setting and other settings proportional or equal to https://golang.org/pkg/math/ constants per arch.

**Comment by shiyanhui** [comment]
Added, and I will close it for now. Feel free to reopen it if there are still problems :)

**Comment by shiyanhui** [comment]
Added, and I will close it for now. Feel free to reopen it if there are still problems :)

**Comment by luckcolors** [comment]
Thanks :)
