### ISSUE TITLE
如何加入dht网络？

### ISSUE THREAD

**Issue by kekemuyu** [shiyanhui/dht#42]
教程《一步一步教你写BT种子嗅探器-DHT篇》的krpc部分提到：
一开始你是不在DHT网络中的，你需要别人把你介绍进去，任何一个在DHT中的人都可以。一般我们可以向 router.bittorrent.com:6881、 dht.transmissionbt.com:6881 等发送find_node请求，然后我们的DHT就可以开始工作了

这样好像还是需要一个有公网ip的网络节点啊，那这个中心节点关掉了不是同样无法工作了？请求老大解惑。同时想请教router.bittorrent.com:6881是如何把新节点介绍进dht网络中去的

**Comment by shiyanhui** [comment]
> 这样好像还是需要一个有公网ip的网络节点啊，那这个中心节点关掉了不是同样无法工作了？
任何一个在dht网络中的节点都行. 关键是找到这个节点.

> 同时想请教router.bittorrent.com:6881是如何把新节点介绍进dht网络中去的
发送find_node等请求的时候, 别的节点会自动把你的地址保存起来, 这样就加入了.

**Comment by shcabin** [comment]
除了"router.bittorrent.com:6881","router.utorrent.com:6881","dht.transmissionbt.com:6881",还有其它类似的节点吗？

**Comment by liian2018** [comment]
为什么我发送find_node请求 然后给我返回的信息部分乱码了。。。

**Comment by happyHeartJ** [comment]
> > 这样好像还是需要一个有公网ip的网络节点啊，那这个中心节点关掉了不是同样无法工作了？
> 
> 任何一个在dht网络中的节点都行. 关键是找到这个节点.
> 
> > 同时想请教router.bittorrent.com:6881是如何把新节点介绍进dht网络中去的
> 
> 发送find_node等请求的时候, 别的节点会自动把你的地址保存起来, 这样就加入了.

如果在第一次运行的时候，不知道任何一个在DHT网络中的节点，怎么去寻找DHT节点？
find_node请求是发送给谁的呢？
麻烦帮忙解答一下，谢谢

**Comment by shcabin** [comment]
> > > 这样好像还是需要一个有公网ip的网络节点啊，那这个中心节点关掉了不是同样无法工作了？
> > 
> > 
> > 任何一个在dht网络中的节点都行. 关键是找到这个节点.
> > > 同时想请教router.bittorrent.com:6881是如何把新节点介绍进dht网络中去的
> > 
> > 
> > 发送find_node等请求的时候, 别的节点会自动把你的地址保存起来, 这样就加入了.
> 
> 如果在第一次运行的时候，不知道任何一个在DHT网络中的节点，怎么去寻找DHT节点？
> find_node请求是发送给谁的呢？
> 麻烦帮忙解答一下，谢谢

我理解是一定要有启动节点的，否则是一个孤立的节点。
