### ISSUE TITLE
find_node no response

### ISSUE THREAD

**Issue by zenghuazhe** [shiyanhui/dht#44]
你好，看了您写的两篇教程非常激动，于是自己用java尝试着写嗅探器
我遇到的问题是：通过对 bootstrap 返回的所有节点 发送find_node请求，竟然没收到一个response， 卡了很久不知道哪里出了问题
bdecode对compact nodes info 里包含的 ip和port的解码应该不会错 ， 请求老哥的帮助

**Comment by zenghuazhe** [comment]
this is in more detail
https://stackoverflow.com/questions/50340371/dht-find-node-no-response

**Comment by shiyanhui** [comment]
请问你是在局域网上跑的吗? 由于NAT原因在局域网里边往往会出现你说的这种情况. 建议在拥有独立ip的服务器上跑一下.

**Comment by zenghuazhe** [comment]
你好，电脑是连的学校wifi(并且开了vpn)。。。我ping了一些ip有些是可以ping通的
您说的独立ip服务器，我在想是不是需要租个阿里云服务器- -

**Comment by shiyanhui** [comment]
连的wifi肯定是NAT网络了, 可以买最便宜的那个套餐试一下. Vultr, 阿里云等都可以.

**Comment by zenghuazhe** [comment]
非常感谢！我去试一下

**Comment by zenghuazhe** [comment]
你好，真的很谢谢你的帮助。我已经收集了大量infohash 以及对应的peers信息， 现在想更进一步， 做一个类似于磁力链接网站那样的搜索功能，就是通过关键字筛选出对应的bt种子(其实只要是有效的磁力链接就行，然后可以直接通过迅雷等解析下载)，想请问一下之后的实现(比如与peers取得联系 获取文件的描述信息,以便于建立 关键字和对应bt种子的索引)可以参考的协议， 以及关键字检索的工具、库。
再次感谢！
