### ISSUE TITLE
代码写的不是很好看.

### ISSUE THREAD

**Issue by yqsy** [shiyanhui/dht#45]
特别是这个函数,看的我胸闷!
func (wire *Wire) fetchMetadata(r Request) 
...

提几个建议
1. 能否运用以下函数减少重复制造轮子:

binary.Read
io.ReadFull

2.能否把同一维度的东西归类写在一起

比如,
这个是一个维度的, 发送握手包,得到握手应答,发送额外握手包
```
	if sendHandshake(conn, infoHash, []byte(randomString(20))) != nil ||
		read(conn, 68, data) != nil ||
		onHandshake(data.Next(68)) != nil ||
		sendExtHandshake(conn) != nil {
		return
	}
```

但下面的代码呢? 读包头4 字节,再读1字节,再读1字节 . 这些不是同一维度的! 140行的函数看的头晕(1个for循环上下文乱跳,一堆暴露在外面的细节)

3. 错误处理能否打个日志.贴个协议注释,链接.

写程序要逻辑清楚干净, 表明清楚意思.这份代码看的我真的难受,提点抱怨,见谅.

**Comment by shiyanhui** [comment]
Hi,

谢谢你提的这些建议, 能提出这些建议说明你认真读代码了。但是根据协议要处理一些很细节的东西，所以有的代码看起来不是太好，但也是没法避免的，当然也有可能是我水平不够。要不你提个PR狠狠地甩我一脸告诉我怎么样做才是“写程序要逻辑干净，表达清楚意思“，才能让你好受点？

谢谢。

**Comment by shiyanhui** [comment]
@yqsy 有什么进展吗?

**Comment by yqsy** [comment]
https://github.com/yqsy/recipes/tree/master/dht

我正在写中,还差路由表,实现kademlia算法..正在研究中

**Comment by LiMoMoMo** [comment]
狠狠地甩你一脸...😄
