### ISSUE TITLE
Spider Shows no result , waits almost 15 minutes for one metadata

### ISSUE THREAD

**Issue by volknanebo** [shiyanhui/dht#49]
How can i improve this ? It giving so slow crawling i think i am doing something wrong . People wrote minimum 100 torrent an hour , but i think i am doing something wrong . I closed firewall even , but still having same problem , Thanks

**Comment by raspher** [comment]
Usually internet providers tend to block traffic. Have you tried VPS?

**Comment by shiyanhui** [comment]
@volknanebo See readme please.
