### ISSUE TITLE
作为一个新人，能麻烦请教下各位怎么用吗？

### ISSUE THREAD

**Issue by vvvoler** [shiyanhui/dht#5]
下了可执行.exe。双击打开或用cmd打开都没反应。请问直接使用是用什么命令呀？
还不是很会编程，才开始学……麻烦大神们了~

**Comment by shiyanhui** [comment]
双击执行就可以啦

**Comment by qinshuguo** [comment]
会有什么结果? 抓取的数据存在哪?

**Comment by shiyanhui** [comment]
会把抓取的结果打印出来，怎么样存储的话还需要你自己实现。https://www.youtube.com/watch?v=AIpeQtw22kc

**Comment by vvvoler** [comment]
双击执行一直是黑屏从来没动过……

**Comment by shiyanhui** [comment]
现在在内网，也就是局域网内还不行，还不能穿透NAT😭 ，接下来我会解决这个问题
