### ISSUE TITLE
6060端口的作用是?

### ISSUE THREAD

**Issue by stormeyes** [shiyanhui/dht#51]
运行起来后, 脚本打开了两个端口, TCP的6060和UDP的6881

6881这个比较好理解, 就是用于peers之间的通信的, 接收查询请求之类的场景.

但是这个6060的是干嘛的呢? 我在代码里面只看到起了一个http的6060的端口, 也不知道这个端口的作用

**Comment by Tanght4123** [comment]
你自己IP:端口看下就知道了

**Comment by shiyanhui** [comment]
这个端口是为了进行pprof性能调优用的.
