### ISSUE TITLE
Spider needs fixing.

### ISSUE THREAD

**Issue by Joepsh** [shiyanhui/dht#54]
The code is not working properly

Sometimes it will find 1 infohash then won't find anymore no matter how long i leave it running.

I have used wireshark to verify that i am receiving see traffic which shows all the peers, infohashes so it's not a network issue.

Also the spider will sometimes send invalid transaction ids which i can see responses via wireshark from peers. I'm not sure if this is a problem but i thought it maybe worth mentioning.

**Comment by shiyanhui** [comment]
Do you run it in a NAT network? DHT doesn't support for that now.

**Comment by Joepsh** [comment]
I added a bit more logging to break it down and now i am now getting results from OnAnnouncePeer which doesn't happen often. Sometimes it does not get the information from the hash and there is no error. Most of what i was seeing in wireshark was from OnGetPeers which explains why i was seeing alot of traffic in wireshark but not in the spider.

Also i noticed some torrent names have weird and disturbing file names i did not expect to see.

I don't know why it wasn't working the first few tries i even left it running while i was a sleep and when i woke up and checked i didn't see anything logged.

Now that i know i can see traffic maybe if i keep it open longer it will gather more.

**Comment by bigcat26** [comment]
Does udp port mapping works in NAT network?
Does port number 6881 must be 6881 ? or I can just use any other port number mapped to my LAN host ?

**Comment by shiyanhui** [comment]
It doesn't have to be 6881. You can set it in config. https://github.com/shiyanhui/dht/blob/master/dht.go#L81

**Comment by shiyanhui** [comment]
This issue is closed for now. Feel free to reopen it if there is problem.
