### ISSUE TITLE
bitmap String() 长度异常

### ISSUE THREAD

**Issue by shichaoyuan** [shiyanhui/dht#7]
文件bitmap.go中String()方法

```go
	for i := 0; i < div; i++ {
		buff[i] = fmt.Sprintf("%04b", bitmap.data[i])
	}
```

因为1byte=8bit，所以这里输出是否应该是"%08b"?

**Comment by shiyanhui** [comment]
嗯，你是对的。天，我咋会写成4，脑子一定进水了。而且测试用例刚好把第0位设置成了1，没有检测出来。已Fix，测试用例也更新了。多谢！
