### ISSUE TITLE
关于NAT传透.

### ISSUE THREAD

**Issue by sickHamm** [shiyanhui/dht#8]
仅作参考。
bep5  应该是自带部分UDP 打洞效果的（Address-Restricted cone NAT  and Port-Restricted cone NAT），你发送过 find_node 或其他任何消息的节点，向你发送get_peer 或 announce_peer 消息应该是可以穿透NAT的（当然一定时间内）， 而通过其他节点的路由表发现你，直接向你发送消息就不可能传透
NAT了。

**Comment by shiyanhui** [comment]
嗯，NAT穿透我还没有仔细研究。我只说下我现在所知道的，一起讨论下。

现在的问题是，在局域网内，我可以对已经知道的IP发送UDP请求，但是我搜不到其UDP回复。

BEP-5规定了DHT相关的规范，并没有提及NAT穿透问题。我查了下[官方文档](http://www.bittorrent.org/beps/bep_0000.html)，BEP-29（uTP协议）貌似可以解决NAT穿透问题，但我印象中uTP是用来下载的（BT默认的下载方式是TCP）。

这里有一个能够透NAT的DHT实现 https://github.com/maidsafe/MaidSafe-DHT，看了下[文档](https://github.com/maidsafe-archive/MaidSafe-Routing/wiki/Documentation#nat-traversal)，NAT穿透是用了hole punching的方式。

**Comment by sickHamm** [comment]
BEP5 没有提及 NAT， 但是从通过bootstrap node 加入dht 网络， 联络大量其他节点，本身就相当于UDP 打洞过程，[参考实现](https://github.com/alanyang/dhtspider)没有什么特殊过程，就可以收到不少get_peers 请求，

> 对已经知道的IP发送UDP请求，但是我收不到其UDP回复
应该是可以收到的，但我不会go， 至于是否能通过nat穿透完全达到外网的效果，我认为不太可能.

**Comment by shiyanhui** [comment]
嗯，这跟语言没关系的，我对NAT穿透还没有研究，等我研究透了再回复你，哈哈
