### ISSUE TITLE
这个能做到直接下载种子的内容吗？

### ISSUE THREAD

**Issue by plokmju88** [shiyanhui/dht#9]
这个能做到直接下载种子的内容吗？如果只是提取到种子，好像也没多大用，最好是能直接下载

**Comment by shiyanhui** [comment]
这个项目主要目的是为了爬DHT网络，不是为了实现BT客户端。后序会考虑把BEP-3实现了，你就可以下载资源了 :)

**Comment by plokmju88** [comment]
期待快些支持，如果可以直接播放的话 我就可以在我家的智能电视上直接播放种子资源了

**Comment by shiyanhui** [comment]
想法不错，哈哈！有空了我就把他实现了，敬请期待！
